export const CREATE_CONTACT = 'CREATE_CONTACT';
export const CREATE_COMPANY = 'CREATE_COMPANY';
export const CREATE_COMPANY_FAILED = 'CREATE_COMPANY_FAILED';
export const CREATE_ST20 = 'CREATE_ST20';
export const CREATE_STO = 'CREATE_STO';
export const CREATE_STO_FAILED = 'CREATE_STO_FAILED';
export const TOGGLE_FORM = 'TOGGLE_FORM';
